[build]
    command="npm run build"
    publish="build"
    base="client"
    functions="netlify-functions"
    
[[redirects]]
    from="/*"
    to="/index.html"
    status=200

[[headers]]
    # Define the path for your functions
    for = "/.netlify/functions/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://moodmeadow.com"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"